name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Setup SQLite
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3

      - name: Run tests
        env: 
         NODE_ENV: test
         JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm test
